server:
  port: 8080 # ??????

spring:
  application:
    name: maternal-health-system

  # ???????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ??????? maternal_health_db ?????? SQL ???
    url: jdbc:mysql://localhost:3306/maternal_health_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root  # <--- ??????????
    password: 123456  # <--- ???????????

# MyBatis Plus ??
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ?????? SQL ???????
    map-underscore-to-camel-case: true # ???????? (user_id -> userId)
  global-config:
    db-config:
      id-type: auto # ??????